[ABW-3015] AccountDetails - Collapse header on scroll
radixdlt/babylon-wallet-ios pull request #1068
Opened 2024-04-02 10:15 UTC by danvleju-rdx

Jira ticket: [ABW-3015](https://radixdlt.atlassian.net/browse/ABW-3015)

## Description
Adds a generic component that creates a collapsible header with a list, used in the Account Details screen.

## Demo
https://github.com/radixdlt/babylon-wallet-ios/assets/163979791/700e9806-48ce-42da-8bb9-98c3215e6908

2024-04-02 13:05 UTC, CyonAlexRDX commented
should we really hide the bar "Tokens" / "NFT" / "Staking" / "Pool" here? I would I expect it to be sticky, but maybe Matt did not want that?

<img width="484" alt="Screenshot 2024-04-02 at 15 03 06" src="https://github.com/radixdlt/babylon-wallet-ios/assets/116169792/579073e7-b9e5-4c01-91c6-6b43c0ba015a">

2024-04-02 14:29 UTC, matiasbzurovski requested changes

2024-04-02 14:29 UTC, matiasbzurovski commented on RadixWallet/Features/AccountDetailsFeature/HeaderListViewContainer.swift
> +		addSubviews(in: uiView)
do we need to remove and add every subview each time? It is adding a small glitch every time the view appears/disappears (it shows the activity indicator for an instant).


https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/8649d9b9-4f3d-40eb-9a8f-2c15af5aff69


![Screenshot 2024-04-02 at 16 27 46](https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/5da45bf9-2a6c-4971-b756-8c8cbb6f1869)

2024-04-03 07:26 UTC, kugel3 requested changes
This looks very nice, but we do have as a goal to remove all usage of Introspect. Could this not be done instead with an GeometryReader/Preference combo until we can require iOS 17? We already have some helpers defined for that.

If you place it on the upmost view in the scrollview, you will be able to get the content offset as long the it is (more or less) visible, but we also know that when it disappears, the header should also be collapsed.

Another option we should consider is to use a UITableView here, we do that in AccountHistory, mostly for performance reasons, but it also makes things like this easier.

2024-04-04 15:26 UTC, GhenadieVP commented
Looks slick, though there are some rough edges, which I am not sure easy are fixable. Here I have few resources in my account, so the scroll content is reduced.
Additionally, some deceleration would be nice when user stops scrolling, but probably I am getting to fancy :)


https://github.com/radixdlt/babylon-wallet-ios/assets/118184705/86a3b176-7db4-49a7-b789-25c8a3a2baea

2024-04-04 18:12 UTC, danvleju-rdx commented
@GhenadieVP Reasonably fancy :). I did some improvements [here](https://github.com/radixdlt/babylon-wallet-ios/pull/1068/commits/58074b8de2d18bcd5910c4c552828e788ae3aa19). Feels much better.

https://github.com/radixdlt/babylon-wallet-ios/assets/163979791/7b575475-2cb9-4a7a-b486-2c5d31d9d01e

2024-04-08 15:36 UTC, matiasbzurovski approved these changes

2024-04-09 07:34 UTC, kugel3 approved these changes

2024-04-09 07:51 UTC, merged