[ABW-3328] Fix NPSSurvey presentation bug
radixdlt/babylon-wallet-ios pull request #1132
Opened 2024-05-22 12:42 UTC by matiasbzurovski

Jira ticket: [ABW-3328](https://radixdlt.atlassian.net/browse/ABW-3328?atlOrigin=eyJpIjoiM2FlOWQwMWRlZDg0NDgxOGExZTA3MDE0OTlmZmFiYjYiLCJwIjoiaiJ9)

## Problem
Until now, `Home` was in charge of presenting the `NPSSurvey` view whenever the conditions were met (10th successful transaction or 3 months since last time shown). However, if the `DappInteractor` was currently presenting its flow on the root view, we could have an overlap of modal presentations. This causes unexpected behaviors on SwiftUI, by presenting only one of the two modals and leaving modal presentation broken during the app run. 

### Solution
I moved away the `NPSSurvey` presentation logic from `Home` to `DappInteractor`. Also, refactored the latter so that it uses the `DestinationReducer` approach that we have on every similar scenario.

## How to test
You can either run on a fresh install and perform 10 transactions, or just update the logic under `NPSSurveyClient+Live`:
```Swift
static func shouldAskUserForFeedback(_ transactionCounter: Int, dateOfLastSubmittedNPSSurvey: Date?) -> Bool {
	return true
}
```

## Bug before & after
You can see on the first video how the completion view wasn't presented, while on the second video both views (NPSSurvey & Completion) are presented sequentially.

| Before | After |
| - | - |
| <video src=https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/ad202ace-b49a-4d08-ad39-ad8ae2f1a06f> | <video src=https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/78d77490-171e-4277-99d4-f666604e7426> |

## Bonus before & after
This wasn't part of the issue, but you can see on the first video how, when performing an asset transfer that triggers the NPSSurvey, such view was only presented when going back to home (which could actually never happen if user stayed on asset details until app close). Now it is presented immediately after dismissing the completion view.
| Before | After |
| - | - |
| <video src=https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/89f6bef8-2392-4c13-b1ab-ba1c0e795b94> | <video src=https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/889dff54-ccc2-4977-b1de-77726ac299fd> |

2024-05-22 12:43 UTC, matiasbzurovski commented on RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift
> -		}
Moved into `Destination`

2024-05-22 12:44 UTC, matiasbzurovski commented on RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift
> -			}
Moved into `func reduce(into state: inout State, presentedAction: Destination.Action)`
[link](https://github.com/radixdlt/babylon-wallet-ios/pull/1132/files#diff-e0da21a3c53a16216da44c31e8e799e020a72c57b6f04d332e0c20306cc49711R284)

2024-05-23 10:31 UTC, danvleju-rdx approved these changes
LGTM, but I would wait for @GhenadieVP's input, as he worked on the NPS survey.
 Perhaps there was an intentional reason for not placing the NPS survey in `DappInteractor`.

2024-05-23 14:13 UTC, CyonAlexRDX commented on RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift
> +		if feedback != nil {
I think this is a good idea. But maybe just check with Matt! If you have not done so already?

2024-05-23 14:13 UTC, CyonAlexRDX approved these changes
Nice! LGTM! Good job!

2024-07-03 09:51 UTC, GhenadieVP requested changes
Looks good, but the condition of increment needs to be updated.

2024-07-03 09:51 UTC, GhenadieVP commented on RadixWallet/Features/DappInteractionFeature/Interactor/DappInteractor.swift
> +			npsSurveyClient.incrementTransactionCompleteCounter()
Note that just `completionDismissed` is not enough, you need to also check that the completion is for a transaction, and not any other interaction(like Login).

You could potentially make use of the presence of `txId` from the completion state.

2024-07-03 13:40 UTC, GhenadieVP approved these changes

2024-07-03 14:00 UTC, merged