[ABW-3565] Show resource details on Asset Transfer
radixdlt/babylon-wallet-ios pull request #1211
Opened 2024-07-11 15:24 UTC by matiasbzurovski

Jira ticket: [ABW-3565](https://radixdlt.atlassian.net/browse/ABW-3566)

## Description
Allows to show resource details on Asset Transfer flow.

## Video

https://github.com/radixdlt/babylon-wallet-ios/assets/164921079/3fcd1793-a484-4590-b6b6-a93822a7e591

2024-07-12 07:48 UTC, GhenadieVP requested changes
When showing Stake Units, Stake claim NFTS and pool units, their respective details screen needs to be shown. Those should not be shown as Fungible or NonFungibleToken details.

See Android Demo for reference -> https://github.com/radixdlt/babylon-wallet-android/pull/1048

2024-07-15 09:26 UTC, GhenadieVP approved these changes
LGTM!
Very nice, some minor comments added.

2024-07-15 09:46 UTC, matiasbzurovski commented on RadixWallet/Features/AssetTransferFeature/Components/TransferAccountList/ReceivingAccount/Asset/NonFungibleResourceAsset+Reducer.swift
> +		public var id: ID { token.id.toRawString() }
Actually the `nftGlobalID` isn't used at all, so removing that var.

2024-07-15 09:47 UTC, matiasbzurovski commented on RadixWallet/Features/AssetTransferFeature/Components/TransferAccountList/ReceivingAccount/Asset/NonFungibleResourceAsset+Reducer.swift
> +	}
if we look at this view + reducer only, then the logical choice would be to remove it. However, given this is used in the context of a parent view (`ResourceAsset.View`) that uses `CaseLet` to define which child view to display (fungible vs non fungible), it adds even more noise if we make one of them a plain SwiftUI view.

2024-07-15 12:45 UTC, merged