[ABW-3531, ABW-3544] Create & Edit persona updates
radixdlt/babylon-wallet-ios pull request #1246
Opened 2024-07-26 10:53 UTC by danvleju-rdx

Jira ticket: [ABW-3531](https://radixdlt.atlassian.net/browse/ABW-3531)
Jira ticket: [ABW-3544](https://radixdlt.atlassian.net/browse/ABW-3544)

## Description
- Updated Create & Edit persona UI
- Removed the old Create screen and unified Create & Edit into a single screen
- Added data fields that was missing on Create screen
- Updated `AppTextField`

## Video
paste link here

2024-07-26 10:55 UTC, danvleju-rdx commented on RadixWallet/Features/EditPersonaFeature/EditPersona/EditPersona.swift
>  public struct EditPersona: Sendable, FeatureReducer {
Didn’t find a better naming that will suit both Create and Edit flows. Open to suggestions.

2024-07-26 12:46 UTC, danvleju-rdx commented on RadixWallet/MIGRATE_TO_SARGON/Stage1/Stage1MigrateToSargon+Persona.swift
> +}
Placed this constant here for now. Could move to Sargon if needed.

2024-07-29 09:34 UTC, matiasbzurovski requested changes
Looking great! Only comment is about the changes to `Hint`, we can discuss that on Slack if you want

2024-07-29 09:48 UTC, danvleju-rdx commented on RadixWallet/Core/DesignSystem/Components/Hint.swift
> +					.textStyle(.body2Regular)
reverted

2024-07-29 10:00 UTC, matiasbzurovski approved these changes

2024-07-30 10:23 UTC, kugel3 commented on RadixWallet/Core/DesignSystem/Components/AppTextField.swift
> +				if primaryHeading != nil || secondaryHeading != nil {
Is this correct? The whole block will be visible if secondaryHeading is non-nil, but it looks like the block will be empty anyway, unless primaryHeading is also non-nil?

2024-07-30 10:28 UTC, kugel3 commented on RadixWallet/Features/CreatePersona/Children/Introduction/IntroductionToPersonas+View.swift
> +		private var introToPersona: some SwiftUI.View {
I would just put this stuff inline, or if you really want to extract it, bring the VStack along. ViewBuilder variables with multiple elements can cause surprises later.

2024-07-30 10:29 UTC, kugel3 commented on RadixWallet/Features/CreatePersona/Children/Introduction/IntroductionToPersonas+View.swift
> +			Text(L10n.CreatePersona.Introduction.title)
This is better, strange that this used to be a variable. Perhaps at some point there were multiple options.

2024-07-30 10:31 UTC, kugel3 approved these changes
Good job. Also add `@Reducer` to the reducer.

2024-07-31 13:28 UTC, kugel3 commented on RadixWallet/Core/DesignSystem/Components/AppTextField.swift
> +				if primaryHeading != nil || secondaryHeading != nil {
Ah, I misread the indentation, I thought that was outside of this `if` block.

2024-08-01 06:56 UTC, merged